In [1]:
import scipy.linalg
from numpy import sin, exp

In [161]:
f_x = lambda x: sin(x / 5.0) * exp(x / 10.0) + 5 * exp(-x / 2.0)

In [3]:
print f_x

<function <lambda> at 0x10ac20398>


In [4]:
polynom_rank = 1
A_1 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

In [5]:
A_1

[[1, 1], [1, 15]]

In [6]:
b_1 = [f_x(1), f_x(15)]

In [7]:
b_1

[3.2522168652714192, 0.63522141957866562]

In [8]:
ans1=scipy.linalg.solve(A_1, b_1)

In [9]:
ans1

array([ 3.43914511, -0.18692825])

In [10]:
map(lambda x: x.round(2), ans1)

[3.4399999999999999, -0.19]

In [11]:
polynom_rank = 2
A_2 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [8 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_2 = [f_x(1), f_x(8), f_x(15)]

ans2=scipy.linalg.solve(A_2, b_2)

polynom_rank = 3
A_3 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [4 ** n for n in range(0, polynom_rank + 1)],
    [10 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_3 = [f_x(1), f_x(4), f_x(10), f_x(15)]


In [12]:
answer = scipy.linalg.solve(A_3, b_3)

map(lambda x: x.round(2), answer)

[4.3600000000000003, -1.3, 0.19, -0.01]

In [13]:
ans2

array([ 3.32512949, -0.06531159, -0.00760104])

In [14]:
print ans2

[ 3.32512949 -0.06531159 -0.00760104]


In [18]:
map(lambda x: x.round(2),ans2)

[3.3300000000000001, -0.070000000000000007, -0.01]

In [143]:
from scipy import optimize
import scipy as sp

In [100]:
 x_min=sp.optimize.minimize(f_x,30)

In [95]:
x_min

      fun: -11.898894665981322
 hess_inv: array([[ 1.67940841]])
      jac: array([ 0.])
  message: 'Optimization terminated successfully.'
     nfev: 21
      nit: 6
     njev: 7
   status: 0
  success: True
        x: array([ 25.880193])

In [62]:
print x_min.x

[ 25.880193]


In [140]:
f_x(25.88)

-11.89889465489723

In [146]:
from scipy import optimize

In [151]:
x_min1=sp.optimize.minimize(f_x,2)

In [129]:
print x_min1

      fun: -11.898894665981322
 hess_inv: array([[ 1.67940841]])
      jac: array([ 0.])
  message: 'Optimization terminated successfully.'
     nfev: 21
      nit: 6
     njev: 7
   status: 0
  success: True
        x: array([ 25.880193])


In [152]:
?sp.optimize.minimize

In [153]:
from matplotlib import pylab as plt

In [165]:
plt.plot (x_min1,f_x)
plt.show()

TypeError: float() argument must be a string or a number

In [24]:
def f():
    return sin(x / 5.0) * exp(x / 10.0) + 5 * exp(-x / 2.0)

In [45]:
print f(1)

TypeError: f() takes no arguments (1 given)

In [30]:
print f

<function f at 0x10e3e56e0>


In [34]:
 x_min1=optimize.minimize(f,[1,30])

TypeError: f() takes no arguments (1 given)

In [37]:
f_x(30)

-5.6122087764737998