In [35]:
import numpy as np

In [36]:
import scipy

In [37]:
import pandas

In [8]:
A1=np.array([[2,1,1],[1,-1,0],[3,-1,2]])

In [9]:
v1=np.array([2,-2,2])

In [10]:
np.linalg.solve(A1,v1)

array([-1.,  1.,  3.])

In [12]:
A2=np.array([[2,5],[3.,5.]])

In [13]:
v2=np.array([30,30])

In [131]:
import numpy.linalg as npl

In [20]:
npl.solve(A2,v2)

array([ 5.,  3.])

In [32]:
A3=np.array([[2.,5.],[1,-10]])

In [33]:
v3=np.array([1,3])

In [34]:
type(v3)

numpy.ndarray

In [34]:
s3=npl.solve(A3,v3)

In [37]:
type(s3)

numpy.ndarray

In [35]:
print s3

[ 1.  -0.2]


In [40]:
npl.solve(A3,npl.solve(A3,v3))

array([ 0.36 ,  0.056])

In [117]:
a11,a12,b1=input().split( )
a21,a22,b2=input().split( )
M1=np.array([[a11,a12],[a21,a22]])
v1=np.array([b1,b2])
r=npl.solve(M1,v1)
print (r[0],r[1])

1 2 3


SyntaxError: invalid syntax (<string>, line 1)

In [104]:
a=input()
for i in range(len(a)):
    a[i]=float(a[i])

1,2,3


TypeError: 'tuple' object does not support item assignment

In [119]:
a11=a11x.split()

AttributeError: 'int' object has no attribute 'split'

In [150]:
s=1,2,3

In [156]:
a=input()

1,2,4


AttributeError: 'tuple' object has no attribute 'float'

In [157]:
?tuple

In [144]:
a=len(a)

TypeError: object of type 'int' has no len()

In [147]:
a=int(a)

In [148]:
a

3

In [149]:
a=split(a)

NameError: name 'split' is not defined

In [135]:
s1=a.split( )

AttributeError: 'tuple' object has no attribute 'split'

In [106]:
a21x,a22x,b2x=input()

1,2,3


In [110]:

for i in range(len(a)):
    a[i]=float(a[i])

TypeError: 'tuple' object does not support item assignment

In [86]:
M1=np.array([[a11,a12],[a21,a22]])

In [87]:
print M1

[[ 1.  0.]
 [ 0.  1.]]


In [88]:
type(M1)

numpy.ndarray

In [89]:
v1=np.array([b1,b2])

In [90]:
print v1

[ 1. -1.]


In [91]:
type (v1)

numpy.ndarray

In [92]:
npl.solve(M1,v1)

array([ 1., -1.])

In [93]:
r=npl.solve(A3,v3)

In [158]:
print (r[0],r[1])

(1.0, -0.20000000000000001)


In [15]:
import pandas

In [16]:
import scipy

In [17]:
import matplotlib

In [165]:
import numpy as np
a11,a12,b1=[int(s) for s in input().split()]
a21,a22,b2=[int(s) for s in input().split()]
M1=np.array([[a11,a12],[a21,a22]])
v1=np.array([b1,b2])
r=np.linalg.solve(M1,v1)
print (r[0],r[1])

1


AttributeError: 'int' object has no attribute 'split'

In [1]:
print 'система'

система


In [ ]:
a11,a12,b1=input().split( )
a21,a22,b2=input().split( )
M1=np.array([[a11,a12],[a21,a22]])
v1=np.array([b1,b2])
r=npl.solve(M1,v1)
print (r[0],r[1])

In [46]:
n=int(input())

2


In [19]:
a=[]
for i in range (n):
    row = input()
    for i in range(len(row)):
        row [i]=int(row[i])
        a.append(row)

1,2,3,4


TypeError: 'tuple' object does not support item assignment

In [49]:
a=[]
for i in range(n):
    for j in range(n+1):
        a[i][j]=int(input())

AttributeError: 'list' object has no attribute 'split'

In [39]:
b=np.array([[1,2,3],[2,3,5]])

In [43]:
b

array([[1, 2, 3],
       [2, 3, 5]])

In [44]:
a

[]