In [25]:
import pandas as pd
import numpy as np

from scipy.stats import pearsonr,ttest_rel
from statsmodels.sandbox.stats.multicomp import multipletests

In [6]:
AUC = pd.read_csv('AUCs.txt', sep = '\t', header = 0)

In [7]:
AUC

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0            adult (sample)  0.763   0.768    0.771      0.798
1             breast cancer  0.599   0.591    0.590      0.569
2   breast cancer wisconsin  0.954   0.971    0.968      0.967
3                       cmc  0.628   0.661    0.654      0.657
4                ionosphere  0.882   0.888    0.886      0.898
5                      iris  0.936   0.931    0.916      0.931
6           liver disorders  0.661   0.668    0.609      0.685
7               lung cancer  0.583   0.583    0.563      0.625
8              lymphography  0.775   0.838    0.866      0.875
9                  mushroom  1.000   1.000    1.000      1.000
10            primary tumor  0.940   0.962    0.965      0.962
11                    rheum  0.619   0.666    0.614      0.669
12                   voting  0.972   0.981    0.975      0.975
13                     wine  0.957   0.978    0.946      0.970

In [8]:
AUC.corr()

C4.5    C4.5+m   C4.5+cf  C4.5+m+cf
C4.5       1.000000  0.991879  0.981828   0.982054
C4.5+m     0.991879  1.000000  0.991622   0.993424
C4.5+cf    0.981828  0.991622  1.000000   0.988264
C4.5+m+cf  0.982054  0.993424  0.988264   1.000000

In [ ]:
AUC.columns=('method','c4','c4m','c4cf','c4mcf')

In [26]:
ttest_rel(AUC.c4,AUC.c4m)

Ttest_relResult(statistic=-2.846237043538884, pvalue=0.01375583084734262)

In [27]:
ttest_rel(AUC.c4,AUC.c4cf)

Ttest_relResult(statistic=-0.44969262291495093, pvalue=0.66033865521980628)

In [29]:
ttest_rel(AUC.c4,AUC.c4mcf)

Ttest_relResult(statistic=-2.7485807055863276, pvalue=0.016582754142328113)

In [30]:
ttest_rel(AUC.c4m,AUC.c4cf)

Ttest_relResult(statistic=1.8995715960484156, pvalue=0.079901720897550946)

In [31]:
ttest_rel(AUC.c4m,AUC.c4mcf)

Ttest_relResult(statistic=-1.3797125910860142, pvalue=0.19094506082959681)

In [32]:
ttest_rel(AUC.c4cf,AUC.c4mcf)

Ttest_relResult(statistic=-2.4731473702801123, pvalue=0.027968540725581408)

In [92]:
s2=[ttest_rel(AUC.c4,AUC.c4m),ttest_rel(AUC.c4,AUC.c4cf),ttest_rel(AUC.c4,AUC.c4mcf),ttest_rel(AUC.c4m,AUC.c4cf),ttest_rel(AUC.c4m,AUC.c4mcf),ttest_rel(AUC.c4cf,AUC.c4mcf)]

In [93]:
a= pd.DataFrame.from_records(s2)

In [94]:
a.columns=['stsat','pvalue']

In [95]:
a.pvalue

0    0.013756
1    0.660339
2    0.016583
3    0.079902
4    0.190945
5    0.027969
Name: pvalue, dtype: float64

In [99]:
multipletests(a.pvalue, 
                                            alpha = 0.05, 
                                            method = 'holm')

(array([False, False, False, False, False, False], dtype=bool),
 array([ 0.08253499,  0.66033866,  0.08291377,  0.23970516,  0.38189012,
         0.11187416]),
 0.008512444610847103,
 0.008333333333333333)

In [100]:
multipletests(a.pvalue, 
                                            alpha = 0.05, 
                                            method = 'fdr_bh')

(array([ True, False,  True, False, False, False], dtype=bool),
 array([ 0.04974826,  0.66033866,  0.04974826,  0.11985258,  0.22913407,
         0.05593708]),
 0.008512444610847103,
 0.008333333333333333)